apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: payment
type: Opaque
stringData:
  # Database credentials
  POSTGRES_DB: payments
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
